### ISSUE TITLE
Hard coded path to your iCloud directory

### ISSUE THREAD

**Issue by Ptujec** [BlackwinMin/launchbar-gallery#1]
I just noted that the path to your iCloud directory is hardcoded. Happy LaunchBar coding ;)

**Comment by BlackwinMin** [comment]
It seems relative paths don't work with `subprocess`. Of course the specific path is confusing, so now I use a place holder instead of a path :D

**Comment by Ptujec** [comment]
That works. You could also read the vault paths from ~/Library/Application Support/obsidian/obsidian.json.
