### ISSUE TITLE
使用 imagemagick 拼接图片的问题

### ISSUE THREAD

**Issue by reichn** [BlackwinMin/launchbar-gallery#3]
image Concact Horizontal/image Concact Horizontal.lbaction/Contents/Scripts/default.sh
之中的path地址可能不适用于homebrew安装的imagemagick，其path地址应为/opt/homebrew/bin/magick

**Comment by BlackwinMin** [comment]
谢谢提醒，如果是 M1 芯片上新安装或重安装的 HomeBrew 确实需要注意这个路径，我在相关动作里注释一下 :D
我没有更新 HomeBrew，直接在 Rosetta 下运行 HomeBrew了，所以一直没有修改相关代码（还不是因为懒 XD）
