### ISSUE TITLE
Missing version numbers

### ISSUE THREAD

**Issue by Ptujec** [BlackwinMin/launchbar-gallery#5]
Hi! I'm working on my Update Action, so I am testing it with some of your actions as well. In the process, I noticed that your actions are lacking version numbers. This, of course, is not ideal if you want to compare versions.

**Comment by BlackwinMin** [comment]
Thank you for reminding me, but I'm very sorry. My real-life work has nothing to do with writing code so It's not economical for me to maintaining versions. In addition, once one action is enough to support my work, I will hardly seek improvement. In fact, almost all actions are never updated. In rare cases, I use version numbers, but it mainly happens in the Keyboard Maestro repository.
